/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.data.VendaData;
import br.com.proj.data.VendaProdutoData;
import br.com.proj.data.ProdutoData;
import br.com.proj.model.Venda;
import br.com.proj.model.VendaProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import br.com.proj.model.Produto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mega
 */
public class Checkout extends javax.swing.JInternalFrame {

    private Venda ven;
    private VendaData DAOVen;
    private VendaProduto venpro;
    private VendaProdutoData DOAVenpro;

    private double precotot;
    private ProdutoData DAOProd;
    private ArrayList<Produto> listaDeProdutos;

    /**
     * Creates new form Checkout
     */
    public Checkout() {
        try {
            initComponents();
            //pro = new Produto();
            ven = new Venda();
            venpro = new VendaProduto();
            DAOVen = new VendaData();
            DOAVenpro = new VendaProdutoData();

            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            mp.setNumRows(0);

            DAOProd = new ProdutoData();
            listaDeProdutos = new ArrayList<>();
            listaDeProdutos = DAOProd.carregarComboP();
            jCProd.removeAllItems();
            jCProd.addItem("Selecione");
            for (Produto p : listaDeProdutos) {
                jCProd.addItem(p.getNomepro());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCProd = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jLSalvar = new javax.swing.JLabel();
        jLCancelar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Checkout");

        jLabel2.setText("Produto:");

        jCProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Quantidade:");

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Quantidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbDados);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total(R$):");

        jLTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLTotal.setText("00.0");

        jLSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/salvar 64x64.png"))); // NOI18N
        jLSalvar.setText("Salvar");
        jLSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSalvarMouseClicked(evt);
            }
        });

        jLCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/cancel 64x64.png"))); // NOI18N
        jLCancelar.setText("Cancelar");
        jLCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCancelarMouseClicked(evt);
            }
        });

        jButton1.setText("Adiconar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCancelar)
                .addGap(55, 55, 55)
                .addComponent(jLSalvar)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(225, 225, 225)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLTotal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCProd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLTotal)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSalvar)
                    .addComponent(jLCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalvarMouseClicked
        try {
            if (validarCampos()) {
                if (preencherObjetoVenda()) {
                    if (DAOVen.incluir(ven)) {
                        JOptionPane.showMessageDialog(this, "Venda realizada com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        //jbCancelarActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao salvar a venda!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                        dispose();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());        
        }

        for (int i = 0; i < jtbDados.getRowCount(); i++) {
            try {
                if (preencherObjetoVendaPro(i)) {
                    if (DOAVenpro.incluir(venpro)) {
                        System.out.println("Salvo com sucesso nxn! "+i);
                        //JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        //jbCancelarActionPerformed(evt);
                    } else {
                        System.out.println("Erro ao salvar! nxn! "+i);
                        //JOptionPane.showMessageDialog(this, "Erro ao salvar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                        dispose();
                    }
                    DAOProd.editarvenda(Integer.parseInt(String.valueOf(jtbDados.getValueAt(i, 2))), Integer.parseInt(String.valueOf(jtbDados.getValueAt(i, 0))));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
                dispose();
                Checkout janela = new Checkout();
                getParent().add(janela);
                janela.setVisible(true);
            }
        }
    }//GEN-LAST:event_jLSalvarMouseClicked

    private void jLCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jLCancelarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double tes, aux;
        if (checar()) {
            //pro.getPreco(listaDeProdutos.get(jCProd.getSelectedIndex() - 1).getPreco());
            tes = listaDeProdutos.get(jCProd.getSelectedIndex() - 1).getPreco();
            aux = tes * (Integer.parseInt(jTQuantidade.getText()));
            precotot += aux;
            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            mp.addRow(new String[]{"" + listaDeProdutos.get(jCProd.getSelectedIndex() - 1).getIdpro(), listaDeProdutos.get(jCProd.getSelectedIndex() - 1).getNomepro(), jTQuantidade.getText(), String.valueOf(listaDeProdutos.get(jCProd.getSelectedIndex() - 1).getPreco()) + ""});
            jLTotal.setText(String.valueOf(precotot));
            jCProd.setSelectedIndex(0);
            jTQuantidade.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linhaSelecionada = jtbDados.getSelectedRow();
        if (linhaSelecionada > -1) {
            double aux1, aux2;
            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            aux1 = Double.parseDouble(String.valueOf(jtbDados.getValueAt(jtbDados.getSelectedRow(), 2)));
            aux2 = Double.parseDouble(String.valueOf(jtbDados.getValueAt(jtbDados.getSelectedRow(), 3)));
            precotot -= (aux1 * aux2);
            jLTotal.setText(String.valueOf(precotot));
            mp.removeRow(jtbDados.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto para excluir!", "Meu sistema",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean validarCampos() {
        if (jtbDados.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum produto adicionado na venda!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    private boolean preencherObjetoVenda() {
        ven.setTotalvenda(Double.parseDouble(jLTotal.getText()));
        return true;
    }
    
    private boolean preencherObjetoVendaPro(int i) throws Exception {
        int aux = 0;
        try{
            aux = Integer.parseInt(DAOVen.ultimavenda());
        }catch (NumberFormatException e){
            System.out.println("Venda não encontrada");
        }
        venpro.setIdpro(Integer.parseInt(String.valueOf(jtbDados.getValueAt(i, 0))));
        venpro.setIdvenda(aux);
        venpro.setQuantidade(Integer.parseInt(String.valueOf(jtbDados.getValueAt(i, 2))));
        return true;
    }

    private boolean checar() {
        int teste = 0;
        if (jCProd.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Informe um Produto!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
            teste++;
        }
        try {
            Integer.parseInt(jTQuantidade.getText());
        } catch (NumberFormatException e) {
            teste++;
            JOptionPane.showMessageDialog(this, "Informe uma Quantidade Valida!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
        }
        if (teste == 0) {
            return true;
        } else {
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCProd;
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLSalvar;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTQuantidade;
    private javax.swing.JTable jtbDados;
    // End of variables declaration//GEN-END:variables
}
