/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.data.CategoriaData;
import javax.swing.JOptionPane;
import br.com.proj.model.Categoria;
import br.com.proj.view.JIFCategoria;

/**
 *
 * @author Mega
 */
public class JIFCategoriaCad extends javax.swing.JInternalFrame {

    private Categoria cat;
    private CategoriaData DAO;
    int acao;
    String s1, s2;

    /**
     * Creates new form JIFCategoriaCad
     */
    public JIFCategoriaCad() {
        try {
            initComponents();

            cat = new Categoria();
            DAO = new CategoriaData();
            acao = 0;
            s1 = new String();
            s2 = new String();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }

    public JIFCategoriaCad(Categoria cat, int acao) {
        this();
        this.cat = cat;
        this.acao = acao;
        //this.s1 = s1;
        //this.s2 = s2;
        alteracao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTNomeCat = new javax.swing.JTextField();
        jTComissaoCat = new javax.swing.JTextField();
        jLSalvar = new javax.swing.JLabel();
        jLCancelar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(514, 318));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Categoria");

        jLabel2.setText("Nome:");

        jLabel3.setText("Comissão (%):");

        jLSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/salvar 64x64.png"))); // NOI18N
        jLSalvar.setText("Salvar");
        jLSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSalvarMouseClicked(evt);
            }
        });

        jLCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/cancel 64x64.png"))); // NOI18N
        jLCancelar.setText("Cancelar");
        jLCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTComissaoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTNomeCat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLCancelar)
                        .addGap(46, 46, 46)
                        .addComponent(jLSalvar)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTComissaoCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSalvar)
                    .addComponent(jLCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalvarMouseClicked
        try {
            if (acao == 2) {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.editar(cat)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //jbCancelarActionPerformed(evt);
                            //JIFCategoria.tabelaini();
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Não foi possível atualizar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            } else {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.incluir(cat)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                            //jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao salvar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_jLSalvarMouseClicked

    private void jLCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCancelarMouseClicked

        dispose();
    }//GEN-LAST:event_jLCancelarMouseClicked
    private boolean validarCampos() {

        String msg = "";

        if (jTNomeCat.getText().length() < 1) {
            msg += "Informe um nome.";
        }

        if (jTComissaoCat.getText().equalsIgnoreCase("")) {
            jTComissaoCat.setText("0");
            //msg += "\nInforme um email válido.";
        }

        if (msg.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Corrija: " + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean preencherObjeto() {

        cat.setNomecat(jTNomeCat.getText());
        cat.setComissao(Double.parseDouble(jTComissaoCat.getText()));
        return true;
    }

    private void alteracao() {
        if (acao == 2) {
            jTNomeCat.setText(cat.getNomecat());
            jTComissaoCat.setText(String.valueOf(cat.getComissao()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTComissaoCat;
    private javax.swing.JTextField jTNomeCat;
    // End of variables declaration//GEN-END:variables
}
