/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.data.FornecedorData;
import javax.swing.JOptionPane;
import br.com.proj.model.Fornecedor;
/**
 *
 * @author Mega
 */
public class JIFFornecedorCad extends javax.swing.JInternalFrame {
    private Fornecedor forn;
    private FornecedorData DAO;
    int acao;
    /**
     * Creates new form JIFFornecedorCad
     */
    public JIFFornecedorCad() {
         try {
            initComponents();
            forn = new Fornecedor();
            DAO = new FornecedorData();
            acao = 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }
    
    public JIFFornecedorCad(Fornecedor forn, int acao) {
        this();
        this.forn = forn;
        this.acao = acao;
        alteracao();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTRazao = new javax.swing.JTextField();
        jTCNPJ = new javax.swing.JFormattedTextField();
        jLSalvar = new javax.swing.JLabel();
        jLCancelar = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Fornecedor");

        jLabel2.setText("Nome Fantasia:");

        jLabel3.setText("Razão Social:");

        jLabel4.setText("CNPJ:");

        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });

        try {
            jTCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/salvar 64x64.png"))); // NOI18N
        jLSalvar.setText("Salvar");
        jLSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSalvarMouseClicked(evt);
            }
        });

        jLCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/cancel 64x64.png"))); // NOI18N
        jLCancelar.setText("Cancelar");
        jLCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTRazao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCNPJ)))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLCancelar)
                .addGap(46, 46, 46)
                .addComponent(jLSalvar)
                .addGap(159, 159, 159))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSalvar)
                    .addComponent(jLCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jLSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalvarMouseClicked
        try {
            if (acao == 2) {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.editar(forn)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //jbCancelarActionPerformed(evt);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Não foi possível atualizar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            } else {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.incluir(forn)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                            //jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao salvar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_jLSalvarMouseClicked

    private void jLCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCancelarMouseClicked

        dispose();
    }//GEN-LAST:event_jLCancelarMouseClicked
    
    private boolean validarCampos() {

        String msg = "";

        if (jTNome.getText().length() < 1) {
            msg += "Informe o Nome Fantasia.";
        }
        if (jTRazao.getText().length() < 1) {
            msg += "Informe a Razão Social.";
        }
        if (jTCNPJ.getText().trim().length()!=18) {
            msg += "Informe o CNPJ correto.";
        }

        if (msg.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Corrija: " + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private boolean preencherObjeto() {
        forn.setNomefor(jTNome.getText());
        forn.setRazfor(jTRazao.getText());
        forn.setCnpj(jTCNPJ.getText());
        return true;
    }
    
    private void alteracao() {
        if (acao == 2) {
            jTNome.setText(forn.getNomefor());
            jTRazao.setText(forn.getRazfor());
            jTCNPJ.setText(forn.getCnpj());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField jTCNPJ;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTRazao;
    // End of variables declaration//GEN-END:variables
}
