/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.data.ProdutoData;
import br.com.proj.data.FornecedorData;
import br.com.proj.data.CategoriaData;
//import br.com.proj.extras.TratarFormularios;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import br.com.proj.model.Produto;
import br.com.proj.model.Fornecedor;
import br.com.proj.model.Categoria;

/**
 *
 * @author Mega
 */
public class JIFProdutoCad extends javax.swing.JInternalFrame {

    private Produto pro;
    private ProdutoData DAO;
    private ArrayList<Produto> listaDeProdutos;
    private int acao = 0;

    private FornecedorData DAOForn;
    private ArrayList<Fornecedor> listaDeFornecedores;

    private CategoriaData DAOCat;
    private ArrayList<Categoria> listaDeCategorias;

    /**
     * Creates new form JIFProdutoCad
     */
    public JIFProdutoCad() {
        try {
            initComponents();
            pro = new Produto();
            DAO = new ProdutoData();
            listaDeProdutos = new ArrayList<>();

            DAOForn = new FornecedorData();
            listaDeFornecedores = new ArrayList<>();
            listaDeFornecedores = DAOForn.carregarComboF();
            jCFor.removeAllItems();
            jCFor.addItem("Selecione");
            for (Fornecedor f : listaDeFornecedores) {
                jCFor.addItem(f.getNomefor());
            }

            DAOCat = new CategoriaData();
            listaDeCategorias = new ArrayList<>();
            listaDeCategorias = DAOCat.carregarComboC();
            jCCat.removeAllItems();
            jCCat.addItem("Selecione");
            for (Categoria c : listaDeCategorias) {
                jCCat.addItem(c.getNomecat());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }
    
    public JIFProdutoCad(Produto pro, int acao) {
        this();
        this.pro = pro;
        this.acao = acao;
        alteracao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCFor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCCat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTProd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTQuant = new javax.swing.JTextField();
        jLSalvar = new javax.swing.JLabel();
        jLCancelar = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produto");

        jLabel2.setText("Fornecedor:");

        jCFor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Categoria:");

        jCCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Preço:");

        jTPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Produto:");

        jLabel6.setText("Quantidade:");

        jLSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/salvar 64x64.png"))); // NOI18N
        jLSalvar.setText("Salvar");
        jLSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSalvarMouseClicked(evt);
            }
        });

        jLCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/cancel 64x64.png"))); // NOI18N
        jLCancelar.setText("Cancelar");
        jLCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLCancelar)
                        .addGap(46, 46, 46)
                        .addComponent(jLSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCFor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCCat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTProd, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jTQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSalvar)
                    .addComponent(jLCancelar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPrecoActionPerformed

    private void jLSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalvarMouseClicked
        try {
            if (acao == 2) {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.editar(pro)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //jbCancelarActionPerformed(evt);
                            //JIFCategoria.tabelaini();
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Não foi possível atualizar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            } else {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.incluir(pro)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                            //jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao salvar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_jLSalvarMouseClicked

    private void jLCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCancelarMouseClicked

        dispose();
    }//GEN-LAST:event_jLCancelarMouseClicked
    private void alteracao() {
        if (acao == 2) {
            jTPreco.setText(String.valueOf(pro.getPreco()));
            jTQuant.setText(String.valueOf(pro.getQuantidade()));
            jTProd.setText(pro.getNomepro());
            jCFor.setSelectedItem(pro.getFornecedor().getNomefor());
            jCCat.setSelectedItem(pro.getCategoria().getNomecat());
        }
    }
    
    private boolean validarCampos() {

        String msg = "";

        if (jTPreco.getText().length() < 1) {
            msg += "Informe o preço do produto.";
        }
        if (jTProd.getText().length() < 1) {
            msg += "Informe o nome do Produto.";
        }
        if (jTQuant.getText().length() < 1) {
            msg += "Informe a quantidade do produto.";
        }
        if (jCCat.getSelectedIndex() == 0) {
            msg += "\nInforme uma categoria.";
        }
        if (jCFor.getSelectedIndex() == 0) {
            msg += "\nInforme o fornecedor.";
        }

        if (msg.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Corrija: " + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private boolean preencherObjeto() {
        
        pro.setCategoria(listaDeCategorias.get(jCCat.getSelectedIndex() - 1));
        pro.setFornecedor(listaDeFornecedores.get(jCFor.getSelectedIndex() - 1));
        pro.setNomepro(jTProd.getText());
        pro.setPreco(Double.parseDouble(jTPreco.getText()));
        pro.setQuantidade(Integer.parseInt(jTQuant.getText()));
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCCat;
    private javax.swing.JComboBox<String> jCFor;
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTPreco;
    private javax.swing.JTextField jTProd;
    private javax.swing.JTextField jTQuant;
    // End of variables declaration//GEN-END:variables
}
