/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.data.UsuarioData;
import br.com.proj.model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Aprendiz
 */
public class JIFUsuarioData extends javax.swing.JInternalFrame {
    int cont;
    private Usuario use;
    private UsuarioData DAO;
    int acao;
 

    /**
     * Creates new form JIFUsuarioData
     */
    public JIFUsuarioData() {
        try {
            initComponents();
            use = new Usuario();
            DAO = new UsuarioData();
            acao = 0;
            cont = 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }
    public JIFUsuarioData(Usuario use, int acao) {
        this();
        this.use = use;
        this.acao = acao;
        alteracao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSalvar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTUser = new javax.swing.JTextField();
        jCTipo = new javax.swing.JComboBox<>();
        jPSenhaUser = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jFTel = new javax.swing.JFormattedTextField();
        jFSal = new javax.swing.JTextField();

        setTitle("Usuário");

        jLSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/salvar 64x64.png"))); // NOI18N
        jLSalvar.setText("Salvar");
        jLSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSalvarMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/cancel 64x64.png"))); // NOI18N
        jLabel2.setText("Cancelar");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cadastro de Usuário");

        jLabel4.setText("Nome:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Senha:");

        jLabel7.setText("Cargo:");

        jLabel8.setText("Salário:");

        jLabel9.setText("Usuário:");

        jCTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Vendedor", "Gerente" }));
        jCTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/olho 64x64.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        try {
            jFTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTUser, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFSal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(jLSalvar)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCTipo, jFTel, jTNome, jTUser});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel6)
                        .addComponent(jTUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLSalvar))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        cont++;
        if (cont % 2 == 0) {
            //jPSenhaUser.setEchoChar((char) 0); //password = JPasswordField
            jPSenhaUser.setEchoChar('*');
            System.out.println("\n------\n1\n" + cont);
        } else {
            //jPSenhaUser.setEchoChar('*');
            jPSenhaUser.setEchoChar((char) 0);
            System.out.println("\n------\n2\n" + cont);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalvarMouseClicked
       try {
            if (acao == 2) {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.editar(use)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            //jbCancelarActionPerformed(evt);
                            //JIFCategoria.tabelaini();
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Não foi possível atualizar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            } else {
                if (validarCampos()) {
                    if (preencherObjeto()) {
                        if (DAO.incluir(use)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                            //jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao salvar!", "Meu sistema", JOptionPane.ERROR_MESSAGE);
                            dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            dispose();
        }
    }//GEN-LAST:event_jLSalvarMouseClicked

    private void jCTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoActionPerformed
    
    private boolean validarCampos() {

        String msg = "";

        if (jTNome.getText().length() < 1) {
            msg += "Informe o nome do usuário./n";
        }
        if (jTUser.getText().length() < 1) {
            msg += "Informe o usuário./n";
        }
        if (jFSal.getText().length() < 1) {
            msg += "Informe o salário do usuário./n";
        }
        if (jFTel.getText().length() < 1) {
            msg += "Informe o telefone do usuário./n";
        }
        if (jPSenhaUser.getText().length() < 1) {
            msg += "Informe a senha do usuário./n";
        }
        if (jCTipo.getSelectedIndex() == 0) {
            msg += "Informe o tipo do usuário./n";
        }

        if (msg.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Corrija: " + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
     private boolean preencherObjeto() {
        use.setNomeUser(jTNome.getText());
        use.setPassUser(jPSenhaUser.getText());
        use.setSalUser(Double.parseDouble(jFSal.getText()));
        use.setTelUser(jFTel.getText());
        use.setUserUser(jTUser.getText());
        if(jCTipo.getSelectedItem().equals("Vendedor")){
                use.setTipoUser(1);
            }else{
                use.setTipoUser(2);
            }
        return true;
    }
    
    private void alteracao() {
        if (acao == 2) {
            jTNome.setText(use.getNomeUser());
            jTUser.setText(use.getUserUser());
            if(use.getTipoUser()==1){
                jCTipo.setSelectedItem("Vendedor");
            }else{
                jCTipo.setSelectedItem("Gerente");
            }
            jFSal.setText(String.valueOf(use.getSalUser()));
            jFTel.setText(use.getTelUser());
            jPSenhaUser.setText(use.getPassUser());    
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCTipo;
    private javax.swing.JTextField jFSal;
    private javax.swing.JFormattedTextField jFTel;
    private javax.swing.JLabel jLSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPSenhaUser;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTUser;
    // End of variables declaration//GEN-END:variables
}
