/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.data.UsuarioData;
import br.com.proj.model.Usuario;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class JIFUsuario extends javax.swing.JInternalFrame {

    private Usuario use;
    private UsuarioData DAO;
    private ArrayList<Usuario> listaDeUsuarios;

    /**
     * Creates new form JIFProduto
     */
    public JIFUsuario() {
        try {
            initComponents();
            use = new Usuario();
            DAO = new UsuarioData();
            listaDeUsuarios = new ArrayList<>();
            tabelaini();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLNovo = new javax.swing.JLabel();
        jLExcluir = new javax.swing.JLabel();
        jLAlterar = new javax.swing.JLabel();
        jLSair = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();

        setTitle("Usuários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/user 64x64.png"))); // NOI18N
        jLabel1.setText("Usuários");

        jLNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/add 64x64.png"))); // NOI18N
        jLNovo.setText("Novo");
        jLNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLNovoMouseClicked(evt);
            }
        });

        jLExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/trash 64x64.png"))); // NOI18N
        jLExcluir.setText("Excluir");
        jLExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExcluirMouseClicked(evt);
            }
        });

        jLAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/alterar 64x64.png"))); // NOI18N
        jLAlterar.setText("Alterar");
        jLAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAlterarMouseClicked(evt);
            }
        });

        jLSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/sair 64x64.png"))); // NOI18N
        jLSair.setText("Sair");
        jLSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLNovo)
                .addGap(18, 18, 18)
                .addComponent(jLAlterar)
                .addGap(18, 18, 18)
                .addComponent(jLExcluir)
                .addGap(18, 18, 18)
                .addComponent(jLSair)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLNovo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
        );

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setText("Pesquisa:");

        jtfPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfPesquisaMouseClicked(evt);
            }
        });
        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyReleased(evt);
            }
        });

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Usuário", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisa))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSairMouseClicked
        dispose();
    }//GEN-LAST:event_jLSairMouseClicked

    private void jtfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyReleased
        try {
            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            mp.setNumRows(0);
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                listaDeUsuarios = DAO.pesquisarGeral();
                for (Usuario use : listaDeUsuarios) {
                    mp.addRow(new String[]{"" + use.getIdUser(), use.getNomeUser(), use.getUserUser(), use.getTelUser() + ""});
                }
            }
            if (jtfPesquisa.getText().length() > 1) {
                listaDeUsuarios = DAO.pesquisar(jtfPesquisa.getText());
                for (Usuario use : listaDeUsuarios) {
                    mp.addRow(new String[]{"" + use.getIdUser(), use.getNomeUser(), use.getUserUser(), use.getTelUser() + ""});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfPesquisaKeyReleased

    private void jtfPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfPesquisaMouseClicked
        try {
            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            mp.setNumRows(0);

            listaDeUsuarios = DAO.pesquisarGeral();
            for (Usuario u : listaDeUsuarios) {
                mp.addRow(new String[]{"" + u.getIdUser(), u.getNomeUser(), "" + u.getUserUser(), "" + u.getTelUser()});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfPesquisaMouseClicked

    private void jLNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNovoMouseClicked
        JIFUsuarioData janela = new JIFUsuarioData();
        getParent().add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jLNovoMouseClicked

    private void jtbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDadosMouseClicked
        try {
            int linhaSelecionada = jtbDados.getSelectedRow();
            if (linhaSelecionada > -1) {
                //s1 = ("" + listaDeCategorias.get(linhaSelecionada).getNomecat());
                //s2 = (String.valueOf(listaDeCategorias.get(linhaSelecionada).getComissao()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jtbDadosMouseClicked

    private void jLAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAlterarMouseClicked
        int linhaSelecionada = jtbDados.getSelectedRow();
        if ((use != null) && (linhaSelecionada > -1)) {
            JIFUsuarioData janela = new JIFUsuarioData(listaDeUsuarios.get(linhaSelecionada), 2);
            getParent().add(janela);
            janela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Usuário Selecionado!", "Meu sistema",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLAlterarMouseClicked

    private void jLExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExcluirMouseClicked
        int linhaSelecionada = jtbDados.getSelectedRow();
        if ((use != null) && (linhaSelecionada > -1)) {
            try {
                if (listaDeUsuarios.get(linhaSelecionada).getTipoUser() == 2) {
                    JOptionPane.showMessageDialog(this, "Impossível excluir um Gerente!");

                } else {
                    if (DAO.excluir(listaDeUsuarios.get(linhaSelecionada).getIdUser())) {
                        JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                        tabelaini();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Usuário Selecionado!", "Meu sistema",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLExcluirMouseClicked

    private void tabelaini() {
        try {
            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            mp.setNumRows(0);
            listaDeUsuarios = DAO.pesquisarGeral();
            for (Usuario use : listaDeUsuarios) {
                mp.addRow(new String[]{"" + use.getIdUser(), use.getNomeUser(), use.getUserUser(), use.getTelUser() + ""});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAlterar;
    private javax.swing.JLabel jLExcluir;
    private javax.swing.JLabel jLNovo;
    private javax.swing.JLabel jLSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbDados;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables
}
