/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.proj.view;

import br.com.proj.model.Usuario;
/**
 *
 * @author daniel
 */
public class telaInicio extends javax.swing.JFrame {
    private Usuario obj;
    /**
     * Creates new form telaInicio
     */
    public telaInicio() {
        initComponents();
        obj = new Usuario();
    }
    public telaInicio(Usuario obj) {
        this();
        this.obj = obj;
        logintipo();

        //alterar label quando alguem logar!!!!!!!!!!!!!!!!!!!!!!!!
        //jlLoginUsuario.setText("Você está logado como: "+obj.getNome());
        
        
//        deixar um botão visivel só quando for um usuario adm!!!!!!!!!!!!!!
//        if(obj.getTipo()==1)
//            jbUsuarios.setEnabled(true);
//        else
//            jbUsuarios.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPAreadeTrabalho = new javax.swing.JDesktopPane();
        jLFornecedores = new javax.swing.JLabel();
        jLCategorias = new javax.swing.JLabel();
        jLProdutos = new javax.swing.JLabel();
        jLUsuarios = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMProduto = new javax.swing.JMenuItem();
        jMCatgoria = new javax.swing.JMenuItem();
        jMFornecedor = new javax.swing.JMenuItem();
        jMUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDPAreadeTrabalho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLFornecedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jLFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/fornecedor 64x64.png"))); // NOI18N
        jLFornecedores.setText("Fornecedores");
        jLFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFornecedoresMouseClicked(evt);
            }
        });

        jLCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCategorias.setForeground(new java.awt.Color(255, 255, 255));
        jLCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/categoria 64x64.png"))); // NOI18N
        jLCategorias.setText("Categorias");
        jLCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCategoriasMouseClicked(evt);
            }
        });

        jLProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProdutos.setForeground(new java.awt.Color(255, 255, 255));
        jLProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/produto 64x64.png"))); // NOI18N
        jLProdutos.setText("Produtos");
        jLProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLProdutos.setInheritsPopupMenu(false);
        jLProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProdutosMouseClicked(evt);
            }
        });

        jLUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jLUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/user 64x64.png"))); // NOI18N
        jLUsuarios.setText("Usuários");
        jLUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLUsuarios.setInheritsPopupMenu(false);
        jLUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLUsuariosMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/venda64x64.png"))); // NOI18N
        jLabel7.setText("Venda");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/proj/images/venda64x64.png"))); // NOI18N
        jLabel8.setText("Compra");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jDPAreadeTrabalho.setLayer(jLFornecedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPAreadeTrabalho.setLayer(jLCategorias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPAreadeTrabalho.setLayer(jLProdutos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPAreadeTrabalho.setLayer(jLUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPAreadeTrabalho.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPAreadeTrabalho.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPAreadeTrabalhoLayout = new javax.swing.GroupLayout(jDPAreadeTrabalho);
        jDPAreadeTrabalho.setLayout(jDPAreadeTrabalhoLayout);
        jDPAreadeTrabalhoLayout.setHorizontalGroup(
            jDPAreadeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPAreadeTrabalhoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLProdutos)
                .addGap(18, 18, 18)
                .addComponent(jLCategorias)
                .addGap(18, 18, 18)
                .addComponent(jLFornecedores)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLUsuarios)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jDPAreadeTrabalhoLayout.setVerticalGroup(
            jDPAreadeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPAreadeTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDPAreadeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLUsuarios)
                    .addComponent(jLFornecedores)
                    .addComponent(jLProdutos)
                    .addComponent(jLCategorias))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        jMProduto.setText("Produtos");
        jMProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMProdutoMouseClicked(evt);
            }
        });
        jMProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMProduto);

        jMCatgoria.setText("Categorias");
        jMCatgoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMCatgoriaMouseClicked(evt);
            }
        });
        jMCatgoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCatgoriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMCatgoria);

        jMFornecedor.setText("Fornecedores");
        jMFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMFornecedorMouseClicked(evt);
            }
        });
        jMFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMFornecedor);

        jMUsuarios.setText("Usuários");
        jMUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair do Sistema");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPAreadeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPAreadeTrabalho)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProdutoActionPerformed
        JIFProduto janela = new JIFProduto();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jMProdutoActionPerformed

    private void jMCatgoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCatgoriaActionPerformed
        JIFCategoria janela = new JIFCategoria();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jMCatgoriaActionPerformed

    private void jMFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFornecedorActionPerformed
        JIFFornecedor janela = new JIFFornecedor();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jMFornecedorActionPerformed

    private void jLProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProdutosMouseClicked
        JIFProduto janela = new JIFProduto();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jLProdutosMouseClicked

    private void jLCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCategoriasMouseClicked
        JIFCategoria janela = new JIFCategoria();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jLCategoriasMouseClicked

    private void jLFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFornecedoresMouseClicked
        JIFFornecedor janela = new JIFFornecedor();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jLFornecedoresMouseClicked

    private void jMProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMProdutoMouseClicked
        
    }//GEN-LAST:event_jMProdutoMouseClicked

    private void jMCatgoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCatgoriaMouseClicked
        
    }//GEN-LAST:event_jMCatgoriaMouseClicked

    private void jMFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMFornecedorMouseClicked
        
    }//GEN-LAST:event_jMFornecedorMouseClicked

    private void jLUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLUsuariosMouseClicked
        JIFUsuario janela = new JIFUsuario();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jLUsuariosMouseClicked

    private void jMUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUsuariosActionPerformed
        JIFUsuario janela = new JIFUsuario();
        jDPAreadeTrabalho.add(janela).setSize(jDPAreadeTrabalho.getSize());
        janela.setVisible(true);
    }//GEN-LAST:event_jMUsuariosActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Checkout janela = new Checkout();
        jDPAreadeTrabalho.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Compras janela = new Compras();
        jDPAreadeTrabalho.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicio().setVisible(true);
            }
        });
    }
    
    private void logintipo(){
        if(obj.getTipoUser()==1){
            jLUsuarios.setEnabled(false);
            jLUsuarios.setVisible(false);
            jMUsuarios.setEnabled(false);
            jMUsuarios.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPAreadeTrabalho;
    private javax.swing.JLabel jLCategorias;
    private javax.swing.JLabel jLFornecedores;
    private javax.swing.JLabel jLProdutos;
    private javax.swing.JLabel jLUsuarios;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMCatgoria;
    private javax.swing.JMenuItem jMFornecedor;
    private javax.swing.JMenuItem jMProduto;
    private javax.swing.JMenuItem jMUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
